apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenges-provider
  namespace: challenges-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: frontend
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
        - name: app-challenges-provider-container
          image: application/challenges-provider:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: PROVIDER_TYPE
              value: "docker"
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-math
  namespace: challenges-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: backend-math
  template:
    metadata:
      labels:
        name: backend-math
    spec:
      containers:
        - name: app-challenges-provider-math-container
          image: application/provider-math:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
            - name: SERVER_PORT
              value: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-history
  namespace: challenges-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: backend-history
  template:
    metadata:
      labels:
        name: backend-history
    spec:
      containers:
        - name: app-challenges-provider-history-container
          image: application/provider-history:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
            - name: SERVER_PORT
              value: "8080"