apiVersion: v1
kind: Service
metadata:
  name: app-challenges-service
  namespace: challenges-demo
spec:
  selector:
    name: frontend
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
