spring:
  application:
    name: challenges-provider

server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8888/eureka/}