version: '2.4'

services:
  challenges-provider:
    image: application/challenges-provider:latest
    depends_on:
      provider-math:
        condition: service_healthy
      provider-history:
        condition: service_healthy
    environment:
      PROVIDER_TYPE: docker
      EUREKA_CLIENT_ENABLED: "false"
    ports:
      - 80:8080

  provider-math:
    image: application/provider-math:latest
    environment:
      EUREKA_CLIENT_ENABLED: "false"
      SERVER_PORT: 8080
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 5

  provider-history:
    image: application/provider-history:latest
    environment:
      EUREKA_CLIENT_ENABLED: "false"
      SERVER_PORT: 8080
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 5